### ISSUE TITLE
ELF Image too big for flashing

### ISSUE THREAD

**Issue by chriamue** [sjm42/esp32ircbot#1]
Hi, thanks for the great project,
when trying to flash on esp32 `target = "xtensa-esp32-espidf"` using

```sh
cargo espflash flash --release --monitor
```

getting error:

```sh
Chip type:         esp32 (revision v1.0)
Crystal frequency: 40MHz
Flash size:        4MB
Features:          WiFi, BT, Dual Core, 240MHz, Coding Scheme None
MAC address:       24:6f:28:7a:a3:c4
Bootloader:        /home/chriamue/temp/esp32ircbot/target/xtensa-esp32-espidf/release/build/esp-idf-sys-c8a784861e73b0c6/out/build/bootloader/bootloader.bin
Partition table:   /home/chriamue/temp/esp32ircbot/target/xtensa-esp32-espidf/release/build/esp-idf-sys-c8a784861e73b0c6/out/build/partition_table/partition-table.bin
Error: espflash::image_too_big (link)

  × Supplied ELF image of 2587024B is too big, and doesn't fit configured app partition of 1048576B
  help: Reduce the size of the binary or increase the size of the app partition.
```

Found some [documentation](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/partition-tables.html#generating-binary-partition-table) about changing partition table using some python scripts.

Do you have experience using the rust tools and can share best practice here?

Thank you,
Christian

**Comment by sjm42** [comment]
Sorry, I have no experience on manipulating partitions on esp32 with Rust.
I have been lucky that all my esp32 devices have the app partition using up almost all of the total flash size as it "should".

Well... also this does not _need_ to be handled with Rust tooling, since it is clearly an oneshot config change.

I found this, but have no experience with it:
https://github.com/esp-rs/esp-idf-part
